#!/bin/sh
# This script is for copying everything in your personal "project" folder into
# a "project_backup" folder in your personal "projectnb" folder on the SCC
# cluster.

export DATAB=/project/crc-nak/<YOUR_USERNAME_HERE>
export DATANB=/projectnb/crc-nak/<YOUR_USERNAME_HERE>

# The name of your main data folder in the above personal project and projectnb
# folders:
export PROJDATA=<YOUR_DATA_DIRECTORY_HERE>

rsync --human-readable --verbose --archive $DATAB/$PROJDATA/* \
    $DATANB/project-backup/$PROJDATA
